import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'ar': {
          'quran_kareem': 'القرآن الكريم',
          'reading_judging': 'اقرأ واستمع إلى القرآن',
          'last_read': 'آخر شيء قرأته',
          'continue_reading': 'استمر في القراءة',
          'quran_surahs': 'سور القرآن الكريم',
          'surah': 'سورة',
          'ayah': 'آية',
          'mecca': 'مكية',
          'madinah': 'مدنية',
          'error_quran': 'حدث خطأ أثناء تحميل قائمة السور المحلية',
          'settings': 'الإعدادات',
          'dark_mode': 'الوضع الداكن',
          'language': 'اللغة',
          'app_name': 'بصيرة',
          'loading': 'جاري تهيئة البيانات...',
          'prayer_times': 'مواقيت الصلاة',
          'quran': 'القرآن الكريم',
          'azkar': 'الأذكار',
          'app_description': 'تطبيق إسلامي شامل',
          'books': 'الكتب الإسلامية',
          'azkar_prayers': 'الأذكار والأدعية',
          'skip': 'تخطي',
          'previous': 'السابق',
          'next': 'التالي',
          'start': 'ابدأ',
          'onboarding_desc_1': 'تطبيق إنتاجي للمسلمين يجمع بين مواقيت الصلاة وإدارة المهام والملاحظات لتعزيز الحياة اليومية بالإيمان',
          'onboarding_desc_2': 'اقرأ واستمع إلى القرآن الكريم مع تفسير وترجمة متعددة اللغات',
          'onboarding_desc_3': 'أذكار الصباح والمساء والتسبيح الإلكتروني لتعزيز ذكرك اليومي',
          'login': 'تسجيل الدخول',
          'register': 'إنشاء حساب',
          'welcome_back': 'مرحباً بعودتك! سجل دخولك للمتابعة',
          'create_account_start': 'أنشئ حساباً جديداً للبدء',
          'full_name': 'الاسم الكامل',
          'phone_number': 'رقم الهاتف',
          'email': 'البريد الإلكتروني',
          'password': 'كلمة المرور',
          'remember_me': 'تذكرني',
          'forgot_password_q': 'نسيت كلمة المرور؟',
          'or_continue_with': 'أو استمر باستخدام',
          'dont_have_account': 'ليس لديك حساب؟',
          'already_have_account': 'لديك حساب بالفعل؟',
          'register_now': 'سجل الآن',
          'reset_password': 'استعادة كلمة المرور',
          'enter_email_reset_desc': 'أدخل بريدك الإلكتروني لإرسال رمز التحقق',
          'default_verification_code': 'رمز التحقق الافتراضي',
          'cancel': 'إلغاء',
          'send': 'إرسال',
          'home': 'الرئيسية',
          'prayer': 'الصلاة',
          'profile': 'حسابي',
          'hijri_symbol': 'هـ',
          'islamic_greeting': 'السلام عليكم ورحمة الله وبركاته',
          'welcome_bseera': 'أهلاً بكم في تطبيق بصيرة',
          'read_and_listen': 'اقرأ واستمع',
          'next_prayer': 'الصلاة القادمة',
          'azkar_title': 'الأذكار',
          'today_azkar': 'أذكار اليوم',
          'tasbeeh_title': 'التسبيح',
          'electronic_rosary': 'المسبحة الإلكترونية',
          'hadith_today': 'حديث اليوم',
          'hadith_content': 'قال رسول الله صلى الله عليه وسلم: "من صلى علي صلاة واحدة صلى الله عليه عشر صلوات"',
          'hadith_narrator': 'رواه مسلم',
          'today_prayer_times': 'مواقيت الصلاة اليوم',
          'islamic_books': 'كتب إسلامية',
          'fajr': 'الفجر',
          'dhuhr': 'الظهر',
          'asr': 'العصر',
          'maghrib': 'المغرب',
          'isha': 'العشاء',
          'my_account': 'حسابي',
          'username': 'اسم المستخدم',
          'profile_image': 'الصورة الشخصية',
          'tap_to_edit': 'اضغط للتعديل',
          'change_password': 'تغيير كلمة المرور',
          'appearance': 'المظهر',
          'dark_mode_sub': 'تفعيل الوضع الداكن للتطبيق',
          'notifications_section': 'الإشعارات',
          'prayer_notifications': 'إشعارات الصلاة',
          'prayer_notifications_sub': 'تفعيل إشعارات أوقات الصلاة',
          'location_title': 'الموقع',
          'location_sub': 'تفعيل تحديد الموقع لحساب أوقات الصلاة',
          'help_support': 'المساعدة والدعم',
          'faq': 'الأسئلة الشائعة',
          'contact_us': 'تواصل معنا',
          'about_us': 'من نحن',
          'share_app': 'مشاركة التطبيق',
          'account_management': 'إدارة الحساب',
          'logout': 'تسجيل الخروج',
          'delete_account': 'حذف الحساب',
          'success_title': 'تم بنجاح',
          'error_title': 'خطأ',
          'image_updated_success': 'تم تغيير الصورة الشخصية بنجاح',
          'image_error': 'حدث خطأ أثناء اختيار الصورة',
          'edit': 'تعديل',
          'enter_new': 'أدخل الجديد لـ',
          'updated_success': 'تم تحديثه بنجاح',
          'save': 'حفظ',
          'change_profile_image': 'تغيير الصورة الشخصية',
          'camera': 'الكاميرا',
          'gallery': 'المعرض',
          'current_password': 'كلمة المرور الحالية',
          'new_password': 'كلمة المرور الجديدة',
          'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
          'password_changed_success': 'تم تغيير كلمة المرور بنجاح',
          'logout_confirm_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
          'delete_account_confirm_msg': 'هل أنت متأكد من رغبتك في حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
          'default_location': 'فلسطين',
          'current_location': 'موقعي الحالي',
          'next_prayer_title': 'الصلاة القادمة',
          'time_left_for': 'متبقي على صلاة',
          'sunrise': 'الشروق',
          'surahs_completed': 'سورة ختمتها',
          'reading_hours': 'ساعة قراءة',
          'tasbeeh_count': 'تسبيحة',
          'recent_activity': 'النشاط الأخير',
          'quick_actions': 'إجراءات سريعة',
          'bookmarks': 'الإشارات المرجعية',
          'reading_history': 'سجل القراءة',
          'favorites': 'المفضلة',
          'settings_title': 'الإعدادات',
          'today': 'اليوم',
          'yesterday': 'أمس',
          'days_ago_2': 'منذ 2 يوم',
          'days_ago_3': 'منذ 3 أيام',
          'week_ago': 'منذ أسبوع',
          'activity_quran': 'ختمت سورة البقرة',
          'activity_hadith': 'قراءة 5 أحاديث',
          'activity_tasbeeh': 'تسبيح 100 مرة',
          'activity_book': 'قراءة كتاب فاتحون صلاة',
          'activity_memorize': 'حفظ 3 آيات جديدة',
          'tasbeeh_app': 'المسبحة الإلكترونية',
          'restart': 'إعادة',
          'undo': 'تراجع',
          'well_done': 'أحسنت!',
          'completed_lap': 'لقد أكملت الدورة رقم',
          'continue': 'استمرار',
          'tap_to_tasbeeh': 'اضغط للتسبيح',
          'subhan_allah': 'سُبْحَانَ اللَّهِ',
          'alhamdulillah': 'الْحَمْدُ لِلَّهِ',
          'allahu_akbar': 'اللَّهُ أَكْبَرُ',
          'la_ilaha_illallah': 'لَا إِلَهَ إِلَّا اللَّهُ',
          'astaghfirullah': 'أَسْتَغْفِرُ اللَّهَ',
          'allahumma_salli': 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ',
          'contact_us_desc': 'نحن هنا لخدمتك! لا تتردد في مراسلتنا إذا كان لديك أي استفسار أو اقتراح.',
          'whatsapp': 'واتساب',
          'exit_app': 'خروج',
        },
        'en': {
          'contact_us': 'Contact Us',
          'contact_us_desc': 'We are here to serve you! Feel free to contact us if you have any questions or suggestions.',
          'email': 'Email',
          'whatsapp': 'WhatsApp',
          'subhan_allah': 'Subhan Allah',
          'alhamdulillah': 'Alhamdulillah',
          'allahu_akbar': 'Allahu Akbar',
          'la_ilaha_illallah': 'La ilaha illallah',
          'astaghfirullah': 'Astaghfirullah',
          'allahumma_salli': 'Allahumma Salli ala Muhammad',
          'exit_app': 'Exit',
          'surahs_completed': 'Surahs Completed',
          'tasbeeh_app': 'Electronic Tasbeeh',
          'restart': 'Reset',
          'undo': 'Undo',
          'well_done': 'Well Done!',
          'completed_lap': 'You completed lap number',
          'continue': 'Continue',
          'tap_to_tasbeeh': 'Tap to Tasbeeh',
          'reading_hours': 'Hours Read',
          'tasbeeh_count': 'Tasbeehs',
          'recent_activity': 'Recent Activity',
          'quick_actions': 'Quick Actions',
          'bookmarks': 'Bookmarks',
          'reading_history': 'Reading History',
          'favorites': 'Favorites',
          'settings_title': 'Settings',
          'today': 'Today',
          'yesterday': 'Yesterday',
          'days_ago_2': '2 days ago',
          'days_ago_3': '3 days ago',
          'week_ago': 'A week ago',
          'activity_quran': 'Completed Surah Al-Baqarah',
          'activity_hadith': 'Read 5 Hadiths',
          'activity_tasbeeh': 'Made Tasbeeh 100 times',
          'activity_book': 'Read Fatehون Prayer book',
          'activity_memorize': 'Memorized 3 new verses',
          'default_location': 'Palestine',
          'current_location': 'Current Location',
          'next_prayer_title': 'Next Prayer',
          'time_left_for': 'Remaining for',
          'sunrise': 'Sunrise',
          'prayer_times': 'Prayer Times',
          'hijri_symbol': 'AH',
          'next_prayer': 'Next Prayer',
          'fajr': 'Fajr',
          'dhuhr': 'Dhuhr',
          'asr': 'Asr',
          'maghrib': 'Maghrib',
          'isha': 'Isha',
          'home': 'Home',
          'quran': 'Quran',
          'settings': 'Settings',
          'my_account': 'My Account',
          'username': 'Username',
          'profile_image': 'Profile Image',
          'tap_to_edit': 'Tap to edit',
          'phone_number': 'Phone Number',
          'change_password': 'Change Password',
          'appearance': 'Appearance',
          'dark_mode_sub': 'Enable dark mode for the app',
          'notifications_section': 'Notifications',
          'prayer_notifications': 'Prayer Notifications',
          'prayer_notifications_sub': 'Enable notifications for prayer times',
          'location_title': 'Location',
          'location_sub': 'Enable location services for prayer calculation',
          'help_support': 'Help & Support',
          'faq': 'FAQs',
          'about_us': 'About Us',
          'share_app': 'Share App',
          'account_management': 'Account Management',
          'logout': 'Logout',
          'delete_account': 'Delete Account',
          'success_title': 'Success',
          'error_title': 'Error',
          'image_updated_success': 'Profile image updated successfully',
          'image_error': 'An error occurred while picking image',
          'edit': 'Edit',
          'enter_new': 'Enter new',
          'updated_success': 'updated successfully',
          'cancel': 'Cancel',
          'save': 'Save',
          'change_profile_image': 'Change Profile Image',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'current_password': 'Current Password',
          'new_password': 'New Password',
          'confirm_new_password': 'Confirm New Password',
          'password_changed_success': 'Password changed successfully',
          'logout_confirm_msg': 'Are you sure you want to logout?',
          'delete_account_confirm_msg': 'Are you sure you want to delete your account? This action cannot be undone.',
          'prayer': 'Prayer',
          'profile': 'Profile',
          'islamic_greeting': 'As-salamu alaykum wa rahmatullahi wa barakatuh',
          'welcome_bseera': 'Welcome to Bseera App',
          'read_and_listen': 'Read & Listen',
          'azkar_title': 'Azkar',
          'today_azkar': 'Daily Azkar',
          'tasbeeh_title': 'Tasbeeh',
          'electronic_rosary': 'Electronic Rosary',
          'hadith_today': 'Hadith of the Day',
          'hadith_content': 'The Messenger of Allah (peace be upon him) said: "Whoever sends blessings upon me once, Allah will send blessings upon him ten times."',
          'hadith_narrator': 'Narrated by Muslim',
          'today_prayer_times': 'Today\'s Prayer Times',
          'islamic_books': 'Islamic Books',
          'login': 'Login',
          'register': 'Register',
          'welcome_back': 'Welcome back! Log in to continue',
          'create_account_start': 'Create a new account to start',
          'full_name': 'Full Name',
          'password': 'Password',
          'remember_me': 'Remember me',
          'forgot_password_q': 'Forgot Password?',
          'or_continue_with': 'Or continue with',
          'dont_have_account': "Don't have an account?",
          'already_have_account': 'Already have an account?',
          'register_now': 'Register Now',
          'reset_password': 'Reset Password',
          'enter_email_reset_desc': 'Enter your email to send the verification code',
          'default_verification_code': 'Default Verification Code',
          'send': 'Send',
          'azkar_prayers': 'Azkar & Prayers',
          'skip': 'Skip',
          'previous': 'Previous',
          'next': 'Next',
          'start': 'Start',
          'onboarding_desc_1': 'A productive app for Muslims combining prayer times, task management, and notes to enhance daily life with faith',
          'onboarding_desc_2': 'Read and listen to the Holy Quran with interpretation and multi-language translation',
          'onboarding_desc_3': 'Morning and evening Azkar and electronic Tasbih to enhance your daily remembrance',
          'quran_kareem': 'Holy Quran',
          'reading_judging': 'Read and listen to the Quran',
          'last_read': 'Last Read',
          'continue_reading': 'Continue Reading',
          'quran_surahs': 'Quran Surahs',
          'surah': 'Surah',
          'ayah': 'Ayah',
          'mecca': 'Meccan',
          'madinah': 'Medinan',
          'error_quran': 'An error occurred while loading local Surahs',
          'dark_mode': 'Dark Mode',
          'language': 'Language',
          'app_name': 'Bseera',
          'app_description': 'Comprehensive Islamic Application',
          'loading': 'Initializing data...',
          'azkar': 'Azkar',
          'books': 'Islamic Books',
        }
      };
}