import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'ar': {
          'quran_kareem': 'القرآن الكريم',
          'reading_judging': 'اقرأ واستمع إلى القرآن',
          'last_read': 'آخر شيء قرأته',
          'no_reading_yet': 'لم تبدأ القراءة بعد',
          'continue_reading': 'استمر في القراءة',
          'quran_surahs': 'سور القرآن الكريم',
          'search_surah': 'ابحث عن سورة',
          'surah': 'سورة',
          'ayah': 'آية',
          'mecca': 'مكية',
          'madinah': 'مدنية',
          'error_quran': 'حدث خطأ أثناء تحميل قائمة السور المحلية',
          'settings': 'الإعدادات',
          'dark_mode': 'الوضع الداكن',
          'language': 'اللغة',
          'app_name': 'بصيرة',
          'loading': 'جاري تهيئة البيانات...',
          'prayer_times': 'مواقيت الصلاة',
          'quran': 'القرآن الكريم',
          'azkar': 'الأذكار',
          'app_description': 'تطبيق إسلامي شامل',
          'books': 'الكتب الإسلامية',
          'azkar_prayers': 'الأذكار والأدعية',
          'skip': 'تخطي',
          'previous': 'السابق',
          'next': 'التالي',
          'start': 'ابدأ',
          'onboarding_desc_1': 'تطبيق إنتاجي للمسلمين يجمع بين مواقيت الصلاة وإدارة المهام والملاحظات لتعزيز الحياة اليومية بالإيمان',
          'onboarding_desc_2': 'اقرأ واستمع إلى القرآن الكريم مع تفسير وترجمة متعددة اللغات',
          'onboarding_desc_3': 'أذكار الصباح والمساء والتسبيح الإلكتروني لتعزيز ذكرك اليومي',
          'login': 'تسجيل الدخول',
          'register': 'إنشاء حساب',
          'welcome_back': 'مرحباً بعودتك! سجل دخولك للمتابعة',
          'create_account_start': 'أنشئ حساباً جديداً للبدء',
          'full_name': 'الاسم الكامل',
          'phone_number': 'رقم الهاتف',
          'email': 'البريد الإلكتروني',
          'password': 'كلمة المرور',
          'remember_me': 'تذكرني',
          'forgot_password_q': 'نسيت كلمة المرور؟',
          'or_continue_with': 'أو استمر باستخدام',
          'dont_have_account': 'ليس لديك حساب؟',
          'already_have_account': 'لديك حساب بالفعل؟',
          'register_now': 'سجل الآن',
          'reset_password': 'استعادة كلمة المرور',
          'enter_email_reset_desc': 'أدخل بريدك الإلكتروني لإرسال رمز التحقق',
          'default_verification_code': 'رمز التحقق الافتراضي',
          'cancel': 'إلغاء',
          'send': 'إرسال',
          'home': 'الرئيسية',
          'prayer': 'الصلاة',
          'profile': 'حسابي',
          'hijri_symbol': 'هـ',
          'islamic_greeting': 'السلام عليكم ورحمة الله وبركاته',
          'welcome_bseera': 'أهلاً بكم في تطبيق بصيرة',
          'read_and_listen': 'اقرأ واستمع',
          'next_prayer': 'الصلاة القادمة',
          'azkar_title': 'الأذكار',
          'today_azkar': 'أذكار اليوم',
          'tasbeeh_title': 'التسبيح',
          'electronic_rosary': 'المسبحة الإلكترونية',
          'hadith_today': 'حديث اليوم',
          'hadith_content': 'قال رسول الله صلى الله عليه وسلم: "من صلى علي صلاة واحدة صلى الله عليه عشر صلوات"',
          'hadith_narrator': 'رواه مسلم',
          'today_prayer_times': 'مواقيت الصلاة اليوم',
          'islamic_books': 'كتب إسلامية',
          'fajr': 'الفجر',
          'dhuhr': 'الظهر',
          'asr': 'العصر',
          'maghrib': 'المغرب',
          'isha': 'العشاء',
          'my_account': 'حسابي',
          'username': 'اسم المستخدم',
          'profile_image': 'الصورة الشخصية',
          'tap_to_edit': 'اضغط للتعديل',
          'change_password': 'تغيير كلمة المرور',
          'appearance': 'المظهر',
          'dark_mode_sub': 'تفعيل الوضع الداكن للتطبيق',
          'notifications_section': 'الإشعارات',
          'prayer_notifications': 'إشعارات الصلاة',
          'prayer_notifications_sub': 'تفعيل إشعارات أوقات الصلاة',
          'location_title': 'الموقع',
          'location_sub': 'تفعيل تحديد الموقع لحساب أوقات الصلاة',
          'help_support': 'المساعدة والدعم',
          'faq': 'الأسئلة الشائعة',
          'contact_us': 'تواصل معنا',
          'about_us': 'من نحن',
          'share_app': 'مشاركة التطبيق',
          'account_management': 'إدارة الحساب',
          'logout': 'تسجيل الخروج',
          'delete_account': 'حذف الحساب',
          'success_title': 'تم بنجاح',
          'error_title': 'خطأ',
          'info_title': 'تنبيه',
          'notifications_enabled_msg': 'تم تفعيل إشعارات أوقات الصلاة',
          'notifications_disabled_msg': 'تم إيقاف إشعارات أوقات الصلاة',
          'image_updated_success': 'تم تغيير الصورة الشخصية بنجاح',
          'image_error': 'حدث خطأ أثناء اختيار الصورة',
          'edit': 'تعديل',
          'enter_new': 'أدخل الجديد لـ',
          'updated_success': 'تم تحديثه بنجاح',
          'save': 'حفظ',
          'change_profile_image': 'تغيير الصورة الشخصية',
          'camera': 'الكاميرا',
          'gallery': 'المعرض',
          'current_password': 'كلمة المرور الحالية',
          'new_password': 'كلمة المرور الجديدة',
          'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
          'password_changed_success': 'تم تغيير كلمة المرور بنجاح',
          'logout_confirm_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
          'delete_account_confirm_msg': 'هل أنت متأكد من رغبتك في حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
          'default_location': 'فلسطين',
          'current_location': 'موقعي الحالي',
          'next_prayer_title': 'الصلاة القادمة',
          'time_left_for': 'متبقي على صلاة',
          'sunrise': 'الشروق',
          'surahs_completed': 'سورة ختمتها',
          'reading_hours': 'ساعة قراءة',
          'tasbeeh_count': 'تسبيحة',
          'recent_activity': 'النشاط الأخير',
          'quick_actions': 'إجراءات سريعة',
          'bookmarks': 'الإشارات المرجعية',
          'reading_history': 'سجل القراءة',
          'favorites': 'المفضلة',
          'no_favorites_yet': 'لا توجد أذكار مفضلة بعد\nاضغط على أيقونة القلب بجانب أي ذكر لإضافته هنا',
          'settings_title': 'الإعدادات',
          'today': 'اليوم',
          'yesterday': 'أمس',
          'days_ago_2': 'منذ 2 يوم',
          'days_ago_3': 'منذ 3 أيام',
          'week_ago': 'منذ أسبوع',
          'activity_quran': 'ختمت سورة البقرة',
          'activity_hadith': 'قراءة 5 أحاديث',
          'activity_tasbeeh': 'تسبيح 100 مرة',
          'activity_book': 'قراءة كتاب فاتحون صلاة',
          'activity_memorize': 'حفظ 3 آيات جديدة',
          'tasbeeh_app': 'المسبحة الإلكترونية',
          'restart': 'إعادة',
          'undo': 'تراجع',
          'well_done': 'أحسنت!',
          'completed_lap': 'لقد أكملت الدورة رقم',
          'continue': 'استمرار',
          'tap_to_tasbeeh': 'اضغط للتسبيح',
          'tasbeeh_settings_title': 'إعدادات المسبحة',
          'vibration_on_tap': 'الاهتزاز عند العد',
          'vibration_on_tap_sub': 'اهتزاز خفيف عند كل تسبيحة',
          'sound_on_lap': 'صوت عند إتمام الدورة',
          'sound_on_lap_sub': 'اهتزاز مختلف عند اكتمال العدد المستهدف',
          'custom_target': 'عدد مخصص',
          'custom_target_sub': 'عيّن هدفاً مختلفاً عن الافتراضي',
          'custom_target_hint': 'أدخل العدد المطلوب',
          'apply': 'تطبيق',
          'subhan_allah': 'سُبْحَانَ اللَّهِ',
          'alhamdulillah': 'الْحَمْدُ لِلَّهِ',
          'allahu_akbar': 'اللَّهُ أَكْبَرُ',
          'la_ilaha_illallah': 'لَا إِلَهَ إِلَّا اللَّهُ',
          'astaghfirullah': 'أَسْتَغْفِرُ اللَّهَ',
          'allahumma_salli': 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ',
          'contact_us_desc': 'نحن هنا لخدمتك! لا تتردد في مراسلتنا إذا كان لديك أي استفسار أو اقتراح.',
          'whatsapp': 'واتساب',
          'Qibla':'القبلة',
          'exit_app': 'خروج',
          // شاشة قراءة القرآن
          'juz': 'الجزء',
          'page': 'صفحة',
          'go_to_page': 'الانتقال إلى صفحة',
          'page_number_hint': 'رقم الصفحة (١ - ٦٠٤)',
          'go': 'انتقال',
          'save_page_as_bookmark': 'حفظ صفحة',
          'as_bookmark_suffix': 'كعلامة مرجعية',
          'note_optional_hint': 'ملاحظة (اختياري)...',
          'bookmark_saved_title': 'تم الحفظ',
          'bookmark_saved_msg': 'تمت إضافة العلامة المرجعية',
          'my_bookmarks_title': 'علاماتي المرجعية',
          'no_bookmarks_yet': 'لا توجد علامات محفوظة بعد',
          'current_juz_title': 'الجزء الحالي',
          'you_are_in_juz': 'أنت الآن بالجزء',
          'of_30_juz': 'من 30',
          'tap_to_reveal': 'اضغط للكشف',
          'font_size': 'حجم الخط',
          'hifz_mode': 'وضع الحفظ',
          'hifz_mode_desc': 'إخفاء الآيات واختبار نفسك بالكشف عليها واحدة تلو الأخرى',
          'search_quran_hint': 'ابحث في آيات القرآن الكريم...',
          'search_min_chars': 'ابدأ الكتابة للبحث في آيات القرآن الكريم',
          'no_results': 'لا توجد نتائج',
          'index': 'الفهرس',
          'juz_tab': 'الأجزاء',
          'pages_tab': 'الصفحات',
          'search': 'بحث',
          'bookmarks_tab': 'علاماتي',
          'share': 'مشاركة',
          'more': 'المزيد',
          'surah_prefix': 'سُورَةُ',
        },
      };
}
